#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2022 10:02:21 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from random import random
from tkinter.constants import *

import tkhtmlview

import payment_history
from database.database import Database
import random


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = payment_history.HtmlWindow(_top1)
    init()
    root.mainloop()

Custom = tkhtmlview.HTMLScrolledText

def init():
    db = Database()

    customer =db.getCustomerById(30)
    history = db.getPaymentInfoByCustomerId(customer.customer_id)

    payments = db.getPayments(customer.customer_id)

    if history is not None:
        history.setCustomer(customer)
        history.setPayments(payments)
        html = history.getHtml()
        _w1.Custom1.set_html(html)
    else:
        _w1.Custom1.set_html("Customer {} payment history not found".format(customer.customer_id))

    db.close()

if __name__ == '__main__':
    payment_history.start_up()




