#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 18, 2022 01:32:03 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import vehicle_search_support

class vehicle_search:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("943x450+1219+391")
        top.minsize(1, 1)
        top.maxsize(3825, 2130)
        top.resizable(1,  1)
        top.title("Vehicle Search")
        top.configure(highlightcolor="black")

        self.top = top
        self.yearValue = tk.StringVar()
        self.makeValue = tk.StringVar()
        self.colorValue = tk.StringVar()

        self.Custom1 = vehicle_search_support.Custom(self.top)
        self.Custom1.place(relx=0.011, rely=0.578, relheight=0.373
                , relwidth=0.621)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.TLabelframe1 = ttk.Labelframe(self.top)
        self.TLabelframe1.place(relx=0.011, rely=0.022, relheight=0.522
                , relwidth=0.976)
        self.TLabelframe1.configure(relief='solid')
        self.TLabelframe1.configure(text='''Tlabelframe''')
        self.TLabelframe1.configure(relief="solid")

        self.TButton1 = ttk.Button(self.TLabelframe1)
        self.TButton1.place(relx=0.848, rely=0.809, height=35, width=128
                , bordermode='ignore')
        self.TButton1.configure(command=vehicle_search_support.do_vehicle_search)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Search''')
        self.TButton1.configure(compound='left')

        self.Year = ttk.Entry(self.TLabelframe1)
        self.Year.place(relx=0.141, rely=0.128, relheight=0.119, relwidth=0.287
                , bordermode='ignore')
        self.Year.configure(textvariable=self.yearValue)
        self.Year.configure(takefocus="")
        self.Year.configure(cursor="xterm")

        self.Make = ttk.Entry(self.TLabelframe1)
        self.Make.place(relx=0.163, rely=0.34, relheight=0.119, relwidth=0.287
                , bordermode='ignore')
        self.Make.configure(textvariable=self.makeValue)
        self.Make.configure(takefocus="")
        self.Make.configure(cursor="xterm")

        self.Color = ttk.Entry(self.TLabelframe1)
        self.Color.place(relx=0.163, rely=0.553, relheight=0.119, relwidth=0.287
                , bordermode='ignore')
        self.Color.configure(textvariable=self.colorValue)
        self.Color.configure(takefocus="")
        self.Color.configure(cursor="xterm")

def start_up():
    vehicle_search_support.main()

if __name__ == '__main__':
    vehicle_search_support.main()




