#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 14, 2022 09:52:15 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import rmn_auto_sales_support

class HomePage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+1896+333")
        top.minsize(1, 1)
        top.maxsize(3825, 2130)
        top.resizable(0,  0)
        top.title("RMN Auto Sales - Home")
        top.configure(highlightcolor="black")

        self.top = top

        self.purchase_car_button = tk.Button(self.top)
        self.purchase_car_button.place(x=20, y=40, height=120, width=158)
        self.purchase_car_button.configure(activebackground="#f9f9f9")
        self.purchase_car_button.configure(borderwidth="2")
        self.purchase_car_button.configure(command=rmn_auto_sales_support.button_click_purchase_car)
        self.purchase_car_button.configure(compound='left')
        self.purchase_car_button.configure(text='''Purchase Car''')

        self.sell_car_button = tk.Button(self.top)
        self.sell_car_button.place(x=210, y=40, height=120, width=158)
        self.sell_car_button.configure(activebackground="#f9f9f9")
        self.sell_car_button.configure(borderwidth="2")
        self.sell_car_button.configure(compound='left')
        self.sell_car_button.configure(text='''Sell Car''')

        self.sell_warranty_button = tk.Button(self.top)
        self.sell_warranty_button.place(x=400, y=40, height=120, width=158)
        self.sell_warranty_button.configure(activebackground="#f9f9f9")
        self.sell_warranty_button.configure(borderwidth="2")
        self.sell_warranty_button.configure(compound='left')
        self.sell_warranty_button.configure(text='''Sell Warranty''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.purchase_car_button_1 = tk.Button(self.top)
        self.purchase_car_button_1.place(x=20, y=220, height=120, width=158)
        self.purchase_car_button_1.configure(activebackground="#f9f9f9")
        self.purchase_car_button_1.configure(borderwidth="2")
        self.purchase_car_button_1.configure(command=rmn_auto_sales_support.button_vehicle_search)
        self.purchase_car_button_1.configure(compound='left')
        self.purchase_car_button_1.configure(text='''Vehicle Search''')

class vehicle_search:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("943x450+1885+815")
        top.minsize(1, 1)
        top.maxsize(3825, 2130)
        top.resizable(0,  0)
        top.title("Vehicle Search")
        top.configure(highlightcolor="black")

        self.top = top

        self.Custom1 = rmn_auto_sales_support.Custom(self.top)
        self.Custom1.place(x=10, y=260, height=168, width=586)

        self.TLabelframe1 = ttk.Labelframe(self.top)
        self.TLabelframe1.place(x=10, y=10, height=235, width=920)
        self.TLabelframe1.configure(relief='solid')
        self.TLabelframe1.configure(text='''Tlabelframe''')
        self.TLabelframe1.configure(relief="solid")

        self.TButton1 = ttk.Button(self.TLabelframe1)
        self.TButton1.place(x=780, y=190, height=35, width=128
                , bordermode='ignore')
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Tbutton''')
        self.TButton1.configure(compound='left')

        self.TEntry1 = ttk.Entry(self.TLabelframe1)
        self.TEntry1.place(x=130, y=30, height=28, width=264
                , bordermode='ignore')
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="xterm")

        self.TEntry1 = ttk.Entry(self.TLabelframe1)
        self.TEntry1.place(x=150, y=80, height=28, width=264
                , bordermode='ignore')
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="xterm")

        self.TEntry1 = ttk.Entry(self.TLabelframe1)
        self.TEntry1.place(x=150, y=130, height=28, width=264
                , bordermode='ignore')
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="xterm")

def start_up():
    rmn_auto_sales_support.main()

if __name__ == '__main__':
    rmn_auto_sales_support.main()




