#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 02, 2022 07:10:27 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import rmn_auto_sales_support

class HomePage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("639x482+784+62")
        top.minsize(1, 1)
        top.maxsize(3825, 2130)
        top.resizable(1,  1)
        top.title("RMN Auto Sales - Home")
        top.configure(highlightcolor="black")

        self.top = top

        self.purchase_car_button = tk.Button(self.top)
        self.purchase_car_button.place(relx=0.031, rely=0.187, height=120
                , width=158)
        self.purchase_car_button.configure(activebackground="#f9f9f9")
        self.purchase_car_button.configure(borderwidth="2")
        self.purchase_car_button.configure(command=rmn_auto_sales_support.button_click_purchase_car)
        self.purchase_car_button.configure(compound='left')
        self.purchase_car_button.configure(text='''Purchase Car''')

        self.sell_car_button = tk.Button(self.top)
        self.sell_car_button.place(relx=0.329, rely=0.187, height=120, width=158)

        self.sell_car_button.configure(activebackground="#f9f9f9")
        self.sell_car_button.configure(borderwidth="2")
        self.sell_car_button.configure(command=rmn_auto_sales_support.sell_vehicle)
        self.sell_car_button.configure(compound='left')
        self.sell_car_button.configure(text='''Sell Car''')

        self.sell_warranty_button = tk.Button(self.top)
        self.sell_warranty_button.place(relx=0.626, rely=0.187, height=120
                , width=158)
        self.sell_warranty_button.configure(activebackground="#f9f9f9")
        self.sell_warranty_button.configure(borderwidth="2")
        self.sell_warranty_button.configure(command=rmn_auto_sales_support.sell_warranty)
        self.sell_warranty_button.configure(compound='left')
        self.sell_warranty_button.configure(text='''Sell Warranty''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.purchase_car_button_1 = tk.Button(self.top)
        self.purchase_car_button_1.place(relx=0.031, rely=0.456, height=120
                , width=158)
        self.purchase_car_button_1.configure(activebackground="#f9f9f9")
        self.purchase_car_button_1.configure(borderwidth="2")
        self.purchase_car_button_1.configure(command=rmn_auto_sales_support.button_vehicle_search)
        self.purchase_car_button_1.configure(compound='left')
        self.purchase_car_button_1.configure(text='''Vehicle Search''')

        self.PaymentsButton = tk.Button(self.top)
        self.PaymentsButton.place(relx=0.329, rely=0.456, height=120, width=158)
        self.PaymentsButton.configure(activebackground="#f9f9f9")
        self.PaymentsButton.configure(borderwidth="2")
        self.PaymentsButton.configure(command=rmn_auto_sales_support.make_payment)
        self.PaymentsButton.configure(compound='left')
        self.PaymentsButton.configure(text='''Payments''')

        self.repair_vehicle_button = tk.Button(self.top)
        self.repair_vehicle_button.place(relx=0.626, rely=0.456, height=120
                , width=158)
        self.repair_vehicle_button.configure(activebackground="#f9f9f9")
        self.repair_vehicle_button.configure(borderwidth="2")
        self.repair_vehicle_button.configure(command=rmn_auto_sales_support.repair_vehicle)
        self.repair_vehicle_button.configure(compound='left')
        self.repair_vehicle_button.configure(text='''Repair Vehicle''')

        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(relx=0.031, rely=0.021, height=34, width=531)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="-family {DejaVu Sans} -size 20 -weight bold")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(anchor='w')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''RMN Auto Sales''')
        self.TLabel1.configure(compound='left')

def start_up():
    rmn_auto_sales_support.main()

if __name__ == '__main__':
    rmn_auto_sales_support.main()




