#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 30, 2022 05:58:26 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import WarrantySaleForm_support

class WarrantySaleForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("843x695+637+835")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Warranty Sale Form")
        top.configure(highlightcolor="black")

        self.top = top
        self.warrantyTitleValue = tk.StringVar()
        self.startDateValue = tk.StringVar()
        self.lengthValue = tk.StringVar()
        self.costValue = tk.StringVar()
        self.deductableValue = tk.StringVar()
        self.salesPersonValue = tk.StringVar()
        self.vehicleValue = tk.StringVar()
        self.customerValue = tk.StringVar()
        self.itemValue = tk.StringVar()
        self.dateValue = tk.StringVar()
        self.totalCostValue = tk.StringVar()
        self.monthlyCostValue = tk.StringVar()

        self.WarrantySales = tk.Label(self.top)
        self.WarrantySales.place(relx=0.014, rely=0.016, height=30, width=820)
        self.WarrantySales.configure(activebackground="#f9f9f9")
        self.WarrantySales.configure(anchor='w')
        self.WarrantySales.configure(compound='left')
        self.WarrantySales.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.WarrantySales.configure(text='''Warranty Sales: Select a salesperson, customer and vehicle''')

        self.SalesPerson = tk.Label(self.top)
        self.SalesPerson.place(relx=0.014, rely=0.081, height=29, width=128)
        self.SalesPerson.configure(activebackground="#f9f9f9")
        self.SalesPerson.configure(anchor='w')
        self.SalesPerson.configure(compound='left')
        self.SalesPerson.configure(text='''Salesperson''')

        self.Customer = tk.Label(self.top)
        self.Customer.place(relx=0.012, rely=0.144, height=29, width=128)
        self.Customer.configure(activebackground="#f9f9f9")
        self.Customer.configure(anchor='w')
        self.Customer.configure(compound='left')
        self.Customer.configure(text='''Customer''')

        self.Vehicle = tk.Label(self.top)
        self.Vehicle.place(relx=0.012, rely=0.216, height=29, width=128)
        self.Vehicle.configure(activebackground="#f9f9f9")
        self.Vehicle.configure(anchor='w')
        self.Vehicle.configure(compound='left')
        self.Vehicle.configure(text='''Vehicle''')

        self.VIN = tk.Text(self.top)
        self.VIN.place(relx=0.403, rely=0.216, relheight=0.047, relwidth=0.224)
        self.VIN.configure(background="white")
        self.VIN.configure(font="TkTextFont")
        self.VIN.configure(relief="flat")
        self.VIN.configure(selectbackground="blue")
        self.VIN.configure(selectforeground="white")
        self.VIN.configure(wrap="word")

        self.Phone = tk.Text(self.top)
        self.Phone.place(relx=0.403, rely=0.072, relheight=0.047, relwidth=0.224)

        self.Phone.configure(background="white")
        self.Phone.configure(font="TkTextFont")
        self.Phone.configure(relief="flat")
        self.Phone.configure(selectbackground="#808080")
        self.Phone.configure(selectforeground="white")
        self.Phone.configure(wrap="word")

        self.Warranty1 = tk.Label(self.top)
        self.Warranty1.place(relx=0.014, rely=0.357, height=29, width=154)
        self.Warranty1.configure(activebackground="#f9f9f9")
        self.Warranty1.configure(anchor='w')
        self.Warranty1.configure(compound='left')
        self.Warranty1.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Warranty1.configure(text='''Warranty 1''')
        self.Warranty1.configure(textvariable=self.warrantyTitleValue)
        self.warrantyTitleValue.set('''Warranty 1''')

        self.StartDate = tk.Label(self.top)
        self.StartDate.place(relx=0.014, rely=0.414, height=29, width=128)
        self.StartDate.configure(activebackground="#f9f9f9")
        self.StartDate.configure(anchor='w')
        self.StartDate.configure(compound='left')
        self.StartDate.configure(text='''Start Date''')

        self.Length = tk.Label(self.top)
        self.Length.place(relx=0.014, rely=0.479, height=29, width=128)
        self.Length.configure(activebackground="#f9f9f9")
        self.Length.configure(anchor='w')
        self.Length.configure(compound='left')
        self.Length.configure(text='''Length''')

        self.Cost = tk.Label(self.top)
        self.Cost.place(relx=0.014, rely=0.542, height=29, width=127)
        self.Cost.configure(activebackground="#f9f9f9")
        self.Cost.configure(anchor='w')
        self.Cost.configure(compound='left')
        self.Cost.configure(text='''Cost''')

        self.Deductible = tk.Label(self.top)
        self.Deductible.place(relx=0.014, rely=0.607, height=29, width=128)
        self.Deductible.configure(activebackground="#f9f9f9")
        self.Deductible.configure(anchor='w')
        self.Deductible.configure(compound='left')
        self.Deductible.configure(text='''Deductible''')

        self.One = tk.Label(self.top)
        self.One.place(relx=0.463, rely=0.633, height=29, width=67)
        self.One.configure(activebackground="#f9f9f9")
        self.One.configure(anchor='w')
        self.One.configure(compound='left')
        self.One.configure(text='''Item''')

        self.StartDateEntry = tk.Entry(self.top)
        self.StartDateEntry.place(relx=0.18, rely=0.414, height=20
                , relwidth=0.171)
        self.StartDateEntry.configure(background="white")
        self.StartDateEntry.configure(font="TkFixedFont")
        self.StartDateEntry.configure(selectbackground="blue")
        self.StartDateEntry.configure(selectforeground="white")
        self.StartDateEntry.configure(textvariable=self.startDateValue)

        self.LengthEntry = tk.Entry(self.top)
        self.LengthEntry.place(relx=0.18, rely=0.479, height=20, relwidth=0.171)
        self.LengthEntry.configure(background="white")
        self.LengthEntry.configure(font="TkFixedFont")
        self.LengthEntry.configure(selectbackground="blue")
        self.LengthEntry.configure(selectforeground="white")
        self.LengthEntry.configure(textvariable=self.lengthValue)

        self.CostEntry = tk.Entry(self.top)
        self.CostEntry.place(relx=0.18, rely=0.542, height=20, relwidth=0.171)
        self.CostEntry.configure(background="white")
        self.CostEntry.configure(font="TkFixedFont")
        self.CostEntry.configure(selectbackground="blue")
        self.CostEntry.configure(selectforeground="white")
        self.CostEntry.configure(textvariable=self.costValue)

        self.DeductibleEntry = tk.Entry(self.top)
        self.DeductibleEntry.place(relx=0.18, rely=0.607, height=20
                , relwidth=0.171)
        self.DeductibleEntry.configure(background="white")
        self.DeductibleEntry.configure(font="TkFixedFont")
        self.DeductibleEntry.configure(selectbackground="blue")
        self.DeductibleEntry.configure(selectforeground="white")
        self.DeductibleEntry.configure(textvariable=self.deductableValue)

        self.ItemsCovered = tk.Label(self.top)
        self.ItemsCovered.place(relx=0.458, rely=0.354, height=29, width=204)
        self.ItemsCovered.configure(activebackground="#f9f9f9")
        self.ItemsCovered.configure(anchor='w')
        self.ItemsCovered.configure(compound='left')
        self.ItemsCovered.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.ItemsCovered.configure(text='''Items Covered''')

        self.AddItem = tk.Button(self.top)
        self.AddItem.place(relx=0.819, rely=0.633, height=24, width=117)
        self.AddItem.configure(command=WarrantySaleForm_support.AddItem)
        self.AddItem.configure(compound='left')
        self.AddItem.configure(pady="0")
        self.AddItem.configure(text='''Add Item''')

        self.AddWarranty = tk.Button(self.top)
        self.AddWarranty.place(relx=0.027, rely=0.671, height=24, width=127)
        self.AddWarranty.configure(command=WarrantySaleForm_support.AddWarranty)
        self.AddWarranty.configure(compound='left')
        self.AddWarranty.configure(pady="0")
        self.AddWarranty.configure(text='''Add Warranty''')

        self.SubmitBottom = tk.Button(self.top)
        self.SubmitBottom.place(relx=0.807, rely=0.95, height=24, width=147)
        self.SubmitBottom.configure(command=WarrantySaleForm_support.SubmitBottom)
        self.SubmitBottom.configure(compound='left')
        self.SubmitBottom.configure(pady="0")
        self.SubmitBottom.configure(text='''Submit''')

        self.SalesPersonTCombobox = ttk.Combobox(self.top)
        self.SalesPersonTCombobox.place(relx=0.167, rely=0.081, relheight=0.037
                , relwidth=0.209)
        self.SalesPersonTCombobox.configure(textvariable=self.salesPersonValue)
        self.SalesPersonTCombobox.configure(takefocus="")

        self.VehicleTCombobox = ttk.Combobox(self.top)
        self.VehicleTCombobox.place(relx=0.166, rely=0.216, relheight=0.037
                , relwidth=0.209)
        self.VehicleTCombobox.configure(textvariable=self.vehicleValue)
        self.VehicleTCombobox.configure(takefocus="")

        self.CustomerTCombobox = ttk.Combobox(self.top)
        self.CustomerTCombobox.place(relx=0.166, rely=0.144, relheight=0.037
                , relwidth=0.209)
        self.CustomerTCombobox.configure(textvariable=self.customerValue)
        self.CustomerTCombobox.configure(takefocus="")

        self.Items1TCombobox = ttk.Combobox(self.top)
        self.Items1TCombobox.place(relx=0.534, rely=0.633, relheight=0.039
                , relwidth=0.28)
        self.Items1TCombobox.configure(textvariable=self.itemValue)
        self.Items1TCombobox.configure(takefocus="")

        self.AddItemScrolledlistbox = ScrolledListBox(self.top)
        self.AddItemScrolledlistbox.place(relx=0.463, rely=0.403, relheight=0.188
                , relwidth=0.51)
        self.AddItemScrolledlistbox.configure(background="white")
        self.AddItemScrolledlistbox.configure(cursor="xterm")
        self.AddItemScrolledlistbox.configure(font="TkFixedFont")
        self.AddItemScrolledlistbox.configure(highlightcolor="#d9d9d9")
        self.AddItemScrolledlistbox.configure(selectbackground="blue")
        self.AddItemScrolledlistbox.configure(selectforeground="white")

        self.AddWarrantyCustom = WarrantySaleForm_support.Custom(self.top)
        self.AddWarrantyCustom.place(relx=0.027, rely=0.718, relheight=0.193
                , relwidth=0.957)

        self.TSeparator1 = ttk.Separator(self.top)
        self.TSeparator1.place(relx=0.012, rely=0.719,  relwidth=0.973)

        self.TSeparator2 = ttk.Separator(self.top)
        self.TSeparator2.place(relx=0.0, rely=0.353,  relwidth=0.996)

        self.TLabel2 = ttk.Label(self.top)
        self.TLabel2.place(relx=0.013, rely=0.291, height=25, width=57)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief="flat")
        self.TLabel2.configure(anchor='w')
        self.TLabel2.configure(justify='left')
        self.TLabel2.configure(text='''Date''')
        self.TLabel2.configure(compound='left')

        self.Date = ttk.Entry(self.top)
        self.Date.place(relx=0.095, rely=0.288, relheight=0.039, relwidth=0.171)
        self.Date.configure(textvariable=self.dateValue)
        self.Date.configure(takefocus="")
        self.Date.configure(cursor="xterm")

        self.TLabel3 = ttk.Label(self.top)
        self.TLabel3.place(relx=0.297, rely=0.288, height=25, width=108)
        self.TLabel3.configure(background="#d9d9d9")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief="flat")
        self.TLabel3.configure(anchor='w')
        self.TLabel3.configure(justify='left')
        self.TLabel3.configure(text='''Total Cost''')
        self.TLabel3.configure(compound='left')

        self.TEntry1 = ttk.Entry(self.top)
        self.TEntry1.place(relx=0.474, rely=0.288, relheight=0.039
                , relwidth=0.17)
        self.TEntry1.configure(textvariable=self.totalCostValue)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="xterm")

        self.MonthlyCost = ttk.Entry(self.top)
        self.MonthlyCost.place(relx=0.783, rely=0.288, relheight=0.039
                , relwidth=0.146)
        self.MonthlyCost.configure(textvariable=self.monthlyCostValue)
        self.MonthlyCost.configure(takefocus="")
        self.MonthlyCost.configure(cursor="xterm")

        self.MonthlyCostLabel = ttk.Label(self.top)
        self.MonthlyCostLabel.place(relx=0.664, rely=0.288, height=25, width=97)
        self.MonthlyCostLabel.configure(background="#d9d9d9")
        self.MonthlyCostLabel.configure(foreground="#000000")
        self.MonthlyCostLabel.configure(font="TkDefaultFont")
        self.MonthlyCostLabel.configure(relief="flat")
        self.MonthlyCostLabel.configure(anchor='w')
        self.MonthlyCostLabel.configure(justify='left')
        self.MonthlyCostLabel.configure(text='''Monthly Cost''')
        self.MonthlyCostLabel.configure(compound='left')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    WarrantySaleForm_support.main()

if __name__ == '__main__':
    WarrantySaleForm_support.main()




