#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 30, 2022 10:09:59 AM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 632x563+996+737
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Warranty Sale Form"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "WarrantySaleForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Warranty Sales: Select a salesperson, customer and vehicle} 
    vTcl:DefineAlias "$top.lab46" "WarrantySales" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Salesperson 
    vTcl:DefineAlias "$top.lab47" "SalesPerson" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Customer 
    vTcl:DefineAlias "$top.lab48" "Customer" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Vehicle 
    vTcl:DefineAlias "$top.lab49" "Vehicle" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but53 \
        -background $vTcl(actual_gui_bg) -command Submit -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but53" "Submit" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Warranty Sales Form} 
    vTcl:DefineAlias "$top.lab54" "WarrantySales_1" vTcl:WidgetProc "WarrantySaleForm" 1
    text $top.tex55 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 154 -wrap word 
    $top.tex55 configure -font "TkTextFont"
    $top.tex55 insert end text
    vTcl:DefineAlias "$top.tex55" "VIN" vTcl:WidgetProc "WarrantySaleForm" 1
    text $top.tex56 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 154 -wrap word 
    $top.tex56 configure -font "TkTextFont"
    $top.tex56 insert end text
    vTcl:DefineAlias "$top.tex56" "Phone" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Warranty 1} 
    vTcl:DefineAlias "$top.lab57" "Warranty1" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Start Date} 
    vTcl:DefineAlias "$top.lab58" "StartDate" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Length 
    vTcl:DefineAlias "$top.lab59" "Length" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Cost 
    vTcl:DefineAlias "$top.lab60" "Cost" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Deductible 
    vTcl:DefineAlias "$top.lab61" "Deductible" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text One 
    vTcl:DefineAlias "$top.lab62" "One" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent63 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 
    vTcl:DefineAlias "$top.ent63" "StartDateEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent64 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 
    vTcl:DefineAlias "$top.ent64" "LengthEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 
    vTcl:DefineAlias "$top.ent65" "CostEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent66 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 
    vTcl:DefineAlias "$top.ent66" "DeductibleEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Items Covered} 
    vTcl:DefineAlias "$top.lab68" "ItemsCovered" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 1 -command AddItem \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Add Item} 
    vTcl:DefineAlias "$top.but69" "AddItem" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but70 \
        -background $vTcl(actual_gui_bg) -command AddWarranty -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Add Warranty} 
    vTcl:DefineAlias "$top.but70" "AddWarranty" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but71 \
        -background $vTcl(actual_gui_bg) -command SubmitBottom -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but71" "SubmitBottom" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo50 \
        -font TkTextFont -textvariable salesPersonValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo50" "SalesPersonTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo51 \
        -font TkTextFont -textvariable vehicleValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "VehicleTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo52 \
        -font TkTextFont -textvariable vehicleValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "CustomerTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo53 \
        -font TkTextFont -textvariable itemValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo53" "Items1TCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr54 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.scr54" "AddItemScrolledlistbox" vTcl:WidgetProc "WarrantySaleForm" 1

    $top.scr54.01 configure -background white \
        -cursor xterm \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    vTcl::widgets::ttk::custom::CreateCmd $top.cus56 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.cus56" "AddWarrantyCustom" vTcl:WidgetProc "WarrantySaleForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.018 -width 0 -relwidth 0.54 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.089 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.475 -y 0 -rely 0.089 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.16 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.696 -y 0 -rely 0.178 -width 137 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.231 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.tex55 \
        -in $top -x 0 -relx 0.047 -y 0 -rely 0.302 -width 0 -relwidth 0.256 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex56 \
        -in $top -x 0 -relx 0.649 -y 0 -rely 0.302 -width 0 -relwidth 0.256 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.391 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.462 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.533 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.604 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.675 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.554 -y 0 -rely 0.462 -width 0 -relwidth 0.09 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 0 -relx 0.206 -y 0 -rely 0.462 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 0 -relx 0.206 -y 0 -rely 0.533 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 0 -relx 0.206 -y 0 -rely 0.604 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent66 \
        -in $top -x 0 -relx 0.206 -y 0 -rely 0.675 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.522 -y 0 -rely 0.391 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.57 -y 0 -rely 0.533 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but70 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.746 -width 127 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 0 -relx 0.759 -y 0 -rely 0.941 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo50 \
        -in $top -x 0 -relx 0.19 -y 0 -rely 0.089 -width 0 -relwidth 0.237 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 0 -relx 0.19 -y 0 -rely 0.16 -width 0 -relwidth 0.237 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 0 -relx 0.68 -y 0 -rely 0.089 -width 0 -relwidth 0.237 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.tCo53 \
        -in $top -x 0 -relx 0.68 -y 0 -rely 0.462 -width 0 -relwidth 0.237 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.scr54 \
        -in $top -x 0 -relx 0.57 -y 0 -rely 0.586 -width 0 -relwidth 0.351 \
        -height 0 -relheight 0.114 -anchor nw -bordermode ignore 
    place $top.cus56 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.799 -width 0 -relwidth 0.481 \
        -height 0 -relheight 0.087 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

