#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  May 01, 2022 02:11:27 PM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 843x695+637+835
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Warranty Sale Form"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "WarrantySaleForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Warranty Sales: Select a salesperson, customer and vehicle} 
    vTcl:DefineAlias "$top.lab46" "WarrantySales" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Salesperson 
    vTcl:DefineAlias "$top.lab47" "SalesPerson" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Customer 
    vTcl:DefineAlias "$top.lab48" "Customer" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Vehicle 
    vTcl:DefineAlias "$top.lab49" "Vehicle" vTcl:WidgetProc "WarrantySaleForm" 1
    text $top.tex55 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -relief flat \
        -selectbackground blue -selectforeground white -width 154 -wrap word 
    $top.tex55 configure -font "TkTextFont"
    $top.tex55 insert end text
    vTcl:DefineAlias "$top.tex55" "VIN" vTcl:WidgetProc "WarrantySaleForm" 1
    text $top.tex56 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -relief flat \
        -selectforeground white -width 154 -wrap word 
    $top.tex56 configure -font "TkTextFont"
    $top.tex56 insert end text
    vTcl:DefineAlias "$top.tex56" "Phone" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Warranty 1} -textvariable warrantyTitleValue 
    vTcl:DefineAlias "$top.lab57" "Warranty1" vTcl:WidgetProc "WarrantySaleForm" 1
    set warrantyTitleValue {Warranty 1}
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Start Date} 
    vTcl:DefineAlias "$top.lab58" "StartDate" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Length 
    vTcl:DefineAlias "$top.lab59" "Length" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Cost 
    vTcl:DefineAlias "$top.lab60" "Cost" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Deductible 
    vTcl:DefineAlias "$top.lab61" "Deductible" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Item 
    vTcl:DefineAlias "$top.lab62" "One" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent63 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable startDateValue -width 144 
    vTcl:DefineAlias "$top.ent63" "StartDateEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent64 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable lengthValue -width 144 
    vTcl:DefineAlias "$top.ent64" "LengthEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable costValue -width 144 
    vTcl:DefineAlias "$top.ent65" "CostEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    entry $top.ent66 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable deductableValue -width 144 
    vTcl:DefineAlias "$top.ent66" "DeductibleEntry" vTcl:WidgetProc "WarrantySaleForm" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Items Covered} 
    vTcl:DefineAlias "$top.lab68" "ItemsCovered" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 1 -command AddItem \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Add Item} 
    vTcl:DefineAlias "$top.but69" "AddItem" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but70 \
        -background $vTcl(actual_gui_bg) -command AddWarranty -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Add Warranty} 
    vTcl:DefineAlias "$top.but70" "AddWarranty" vTcl:WidgetProc "WarrantySaleForm" 1
    button $top.but71 \
        -background $vTcl(actual_gui_bg) -command SubmitBottom -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but71" "SubmitBottom" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo50 \
        -font TkTextFont -textvariable salesPersonValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo50" "SalesPersonTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo51 \
        -font TkTextFont -textvariable vehicleValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "VehicleTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo52 \
        -font TkTextFont -textvariable customerValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "CustomerTCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::combobox $top.tCo53 \
        -font TkTextFont -textvariable itemValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo53" "Items1TCombobox" vTcl:WidgetProc "WarrantySaleForm" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr54 \
        -background $vTcl(actual_gui_bg) -height 131 -highlightcolor black \
        -width 430 
    vTcl:DefineAlias "$top.scr54" "AddItemScrolledlistbox" vTcl:WidgetProc "WarrantySaleForm" 1

    $top.scr54.01 configure -background white \
        -cursor xterm \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    vTcl::widgets::ttk::custom::CreateCmd $top.cus56 \
        -background $vTcl(actual_gui_bg) -height 134 -highlightcolor black \
        -width 807 
    vTcl:DefineAlias "$top.cus56" "AddWarrantyCustom" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::separator $top.tSe71
    vTcl:DefineAlias "$top.tSe71" "TSeparator1" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::separator $top.tSe72
    vTcl:DefineAlias "$top.tSe72" "TSeparator2" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::label $top.tLa73 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text Date \
        -compound left 
    vTcl:DefineAlias "$top.tLa73" "TLabel2" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::entry $top.tEn74 \
        -font TkTextFont -textvariable dateValue -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn74" "Date" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::label $top.tLa75 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Total Cost} -compound left 
    vTcl:DefineAlias "$top.tLa75" "TLabel3" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::entry $top.tEn76 \
        -font TkTextFont -textvariable totalCostValue -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn76" "TEntry1" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::entry $top.tEn77 \
        -font TkTextFont -textvariable monthlyCostValue -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$top.tEn77" "MonthlyCost" vTcl:WidgetProc "WarrantySaleForm" 1
    ttk::label $top.tLa78 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {Monthly Cost} -compound left 
    vTcl:DefineAlias "$top.tLa78" "MonthlyCostLabel" vTcl:WidgetProc "WarrantySaleForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.016 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.081 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.144 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.216 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.tex55 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.216 -width 0 -relwidth 0.224 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.tex56 \
        -in $top -x 0 -relx 0.403 -y 0 -rely 0.072 -width 0 -relwidth 0.225 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.357 -width 0 -relwidth 0.183 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.414 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.479 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.542 -width 0 -relwidth 0.151 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.607 -width 0 -relwidth 0.152 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.463 -y 0 -rely 0.633 -width 0 -relwidth 0.079 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.ent63 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.414 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.479 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.542 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent66 \
        -in $top -x 0 -relx 0.18 -y 0 -rely 0.607 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.458 -y 0 -rely 0.354 -width 0 -relwidth 0.242 \
        -height 0 -relheight 0.042 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.819 -y 0 -rely 0.633 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but70 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.671 -width 127 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 0 -relx 0.807 -y 0 -rely 0.95 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo50 \
        -in $top -x 0 -relx 0.167 -y 0 -rely 0.081 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 0 -relx 0.166 -y 0 -rely 0.216 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 0 -relx 0.166 -y 0 -rely 0.144 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.tCo53 \
        -in $top -x 0 -relx 0.534 -y 0 -rely 0.633 -width 0 -relwidth 0.28 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.scr54 \
        -in $top -x 0 -relx 0.463 -y 0 -rely 0.403 -width 0 -relwidth 0.51 \
        -height 0 -relheight 0.188 -anchor nw -bordermode ignore 
    place $top.cus56 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.718 -width 0 -relwidth 0.957 \
        -height 0 -relheight 0.193 -anchor nw -bordermode ignore 
    place $top.tSe71 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.719 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.003 -anchor nw -bordermode ignore 
    place $top.tSe72 \
        -in $top -x 0 -y 0 -rely 0.353 -width 0 -relwidth 0.996 -height 0 \
        -relheight 0.003 -anchor nw -bordermode ignore 
    place $top.tLa73 \
        -in $top -x 0 -relx 0.013 -y 0 -rely 0.291 -width 0 -relwidth 0.068 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.tEn74 \
        -in $top -x 0 -relx 0.095 -y 0 -rely 0.288 -width 144 -relwidth 0 \
        -height 27 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa75 \
        -in $top -x 0 -relx 0.297 -y 0 -rely 0.288 -width 0 -relwidth 0.128 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.tEn76 \
        -in $top -x 0 -relx 0.474 -y 0 -rely 0.288 -width 143 -relwidth 0 \
        -height 27 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tEn77 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.288 -width 123 -relwidth 0 \
        -height 27 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa78 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.288 -width 0 -relwidth 0.115 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

