#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 29, 2022 09:17:03 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import WarrantySaleForm

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = WarrantySaleForm.WarrantySaleForm(_top1)
    root.mainloop()

def AddItem(*args):
    print('WarrantySaleForm_support.AddItem')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def AddWarranty(*args):
    print('WarrantySaleForm_support.AddWarranty')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Submit(*args):
    print('WarrantySaleForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def SubmitBottom(*args):
    print('WarrantySaleForm_support.SubmitBottom')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

Custom = tk.Frame  # To be updated by user with name of custom widget.

if __name__ == '__main__':
    WarrantySaleForm.start_up()




