#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  May 03, 2022 02:12:27 PM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 937x714+731+120
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Car Purchase Form"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "CarPurchaseForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Purchase 
    vTcl:DefineAlias "$top.lab46" "Purchase" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Date 
    vTcl:DefineAlias "$top.lab47" "Date" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Location 
    vTcl:DefineAlias "$top.lab48" "Location" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Make 
    vTcl:DefineAlias "$top.lab49" "Make" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Model 
    vTcl:DefineAlias "$top.lab50" "Model" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Year 
    vTcl:DefineAlias "$top.lab51" "Year" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Miles 
    vTcl:DefineAlias "$top.lab52" "Miles" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Condition 
    vTcl:DefineAlias "$top.lab53" "Condition" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {List Price} 
    vTcl:DefineAlias "$top.lab54" "Model_1_1_1_1" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Sales Price} 
    vTcl:DefineAlias "$top.lab55" "SalesPrice" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Style 
    vTcl:DefineAlias "$top.lab56" "Style" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Interior Color} 
    vTcl:DefineAlias "$top.lab57" "InteriorColor" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor #ffffff \
        -text {Vehicle 1} -textvariable vehicleTitleValue 
    vTcl:DefineAlias "$top.lab58" "Vehicle1" vTcl:WidgetProc "CarPurchaseForm" 1
    set vehicleTitleValue {Vehicle 1}
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Seller/Dealer 
    vTcl:DefineAlias "$top.lab70" "SellerDealer" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab71 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {Tax ID} 
    vTcl:DefineAlias "$top.lab71" "TaxId" vTcl:WidgetProc "CarPurchaseForm" 1
    button $top.but74 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command AddVehicle -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Add Vehicle} 
    vTcl:DefineAlias "$top.but74" "Button1" vTcl:WidgetProc "CarPurchaseForm" 1
    button $top.but75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command Submit -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but75" "Submit" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent76 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable dateValue -width 134 
    vTcl:DefineAlias "$top.ent76" "DateEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable locationValue -width 134 
    vTcl:DefineAlias "$top.ent46" "LocationEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable makeValue -width 134 
    vTcl:DefineAlias "$top.ent47" "MakeEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable modleValue -width 134 
    vTcl:DefineAlias "$top.ent48" "ModelEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent49 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable yearValue -width 134 
    vTcl:DefineAlias "$top.ent49" "YearEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent50 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable milesValue -width 134 
    vTcl:DefineAlias "$top.ent50" "MilesEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable conditionValue -width 134 
    vTcl:DefineAlias "$top.ent51" "ConditionEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent52 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable listPriceValue -width 134 
    vTcl:DefineAlias "$top.ent52" "ListEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent53 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable salePriceValue -width 134 
    vTcl:DefineAlias "$top.ent53" "SalesPriceEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent54 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable styleValue -width 134 
    vTcl:DefineAlias "$top.ent54" "StyleEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent55 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable interiorValue -width 134 
    vTcl:DefineAlias "$top.ent55" "InteriorColorEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent57 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable taxIDValue -width 134 
    vTcl:DefineAlias "$top.ent57" "TaxIDEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    vTcl::widgets::ttk::custom::CreateCmd $top.cus56 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.cus56" "Custom2" vTcl:WidgetProc "CarPurchaseForm" 1
    vTcl::widgets::ttk::custom::CreateCmd $top.cus57 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.cus57" "Custom3" vTcl:WidgetProc "CarPurchaseForm" 1
    ttk::label $top.tLa58 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Vehicle Problems} \
        -compound left 
    vTcl:DefineAlias "$top.tLa58" "TLabel1" vTcl:WidgetProc "CarPurchaseForm" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu59 \
        -command randomData -takefocus {} -text Demo -compound left 
    vTcl:DefineAlias "$top.tBu59" "TButton1" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text VIN 
    vTcl:DefineAlias "$top.lab60" "VIN" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent61 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable vinValue -width 134 
    vTcl:DefineAlias "$top.ent61" "VINEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Color 
    vTcl:DefineAlias "$top.lab62" "InteriorColor" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent63 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable colorValue -width 134 
    vTcl:DefineAlias "$top.ent63" "ColorEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Book Value} 
    vTcl:DefineAlias "$top.lab64" "SalesPrice" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable bookValue -width 134 
    vTcl:DefineAlias "$top.ent65" "BookEntry" vTcl:WidgetProc "CarPurchaseForm" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Price Paid} 
    vTcl:DefineAlias "$top.lab66" "PricePaid" vTcl:WidgetProc "CarPurchaseForm" 1
    entry $top.ent67 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable bookValue -width 134 
    vTcl:DefineAlias "$top.ent67" "BookEntry_1" vTcl:WidgetProc "CarPurchaseForm" 1
    ttk::combobox $top.tCo54 \
        -font TkTextFont -textvariable sellerValue -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo54" "SellerComboBox" vTcl:WidgetProc "CarPurchaseForm" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu55 \
        -command addProblem -takefocus {} -text {Add Problem} -compound left 
    vTcl:DefineAlias "$top.tBu55" "TButton2" vTcl:WidgetProc "CarPurchaseForm" 1
    ttk::label $top.tLa56 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor w -justify left -text {Vehicle Purchase List} \
        -compound left 
    vTcl:DefineAlias "$top.tLa56" "TLabel1_1" vTcl:WidgetProc "CarPurchaseForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 12 -y 13 -width 130 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 12 -y 43 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 351 -y 87 -width 89 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 160 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 280 -y 158 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 581 -y 156 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 280 -y 190 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 580 -y 190 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 10 -y 360 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 10 -y 400 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 10 -y 236 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 10 -y 320 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 10 -y 120 -width 130 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 350 -y 50 -width 109 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 630 -y 90 -width 79 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 720 -y 480 -width 197 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 750 -y 680 -width 177 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 110 -y 49 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 450 -y 90 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 120 -y 160 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 410 -y 160 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 700 -y 160 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 410 -y 190 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 700 -y 190 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 120 -y 360 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 120 -y 400 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 120 -y 240 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 120 -y 320 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 710 -y 90 -width 134 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cus56 \
        -in $top -x 20 -y 560 -width 906 -relwidth 0 -height 115 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cus57 \
        -in $top -x 270 -y 260 -width 646 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa58 \
        -in $top -x 270 -y 230 -width 177 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu59 \
        -in $top -x 280 -y 480 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 10 -y 200 -width 109 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.ent61 \
        -in $top -x 120 -y 200 -width 134 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab62 \
        -in $top -x 10 -y 280 -width 109 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.ent63 \
        -in $top -x 121 -y 283 -width 134 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab64 \
        -in $top -x 10 -y 440 -width 109 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.ent65 \
        -in $top -x 120 -y 440 -width 134 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab66 \
        -in $top -x 10 -y 486 -width 109 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.ent67 \
        -in $top -x 120 -y 490 -width 134 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.tCo54 \
        -in $top -x 450 -y 50 -anchor nw -bordermode ignore 
    place $top.tBu55 \
        -in $top -x 820 -y 420 -anchor nw -bordermode ignore 
    place $top.tLa56 \
        -in $top -x 10 -y 530 -width 177 -height 25 -anchor nw \
        -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

