#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 28, 2022 05:59:15 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import CarPurchaseForm_support

class CarPurchaseForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("937x714+2086+1080")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0,  0)
        top.title("Car Purchase Form")
        top.configure(highlightcolor="black")

        self.top = top
        self.dateValue = tk.StringVar()
        self.locationValue = tk.StringVar()
        self.makeValue = tk.StringVar()
        self.modleValue = tk.StringVar()
        self.yearValue = tk.StringVar()
        self.milesValue = tk.StringVar()
        self.conditionValue = tk.StringVar()
        self.listPriceValue = tk.StringVar()
        self.salePriceValue = tk.StringVar()
        self.styleValue = tk.StringVar()
        self.interiorValue = tk.StringVar()
        self.sellerValue = tk.StringVar()
        self.taxIDValue = tk.StringVar()
        self.vinValue = tk.StringVar()
        self.colorValue = tk.StringVar()
        self.bookValue = tk.StringVar()
        self.pricePaidValue = tk.StringVar()

        self.Purchase = tk.Label(self.top)
        self.Purchase.place(x=12, y=13, height=27, width=130)
        self.Purchase.configure(activebackground="#f9f9f9")
        self.Purchase.configure(anchor='w')
        self.Purchase.configure(compound='left')
        self.Purchase.configure(text='''Purchase''')

        self.Date = tk.Label(self.top)
        self.Date.place(x=10, y=50, height=27, width=109)
        self.Date.configure(activebackground="#f9f9f9")
        self.Date.configure(anchor='w')
        self.Date.configure(compound='left')
        self.Date.configure(text='''Date''')

        self.Location = tk.Label(self.top)
        self.Location.place(x=10, y=90, height=27, width=109)
        self.Location.configure(activebackground="#f9f9f9")
        self.Location.configure(anchor='w')
        self.Location.configure(compound='left')
        self.Location.configure(text='''Location''')

        self.Make = tk.Label(self.top)
        self.Make.place(x=10, y=160, height=27, width=109)
        self.Make.configure(activebackground="#f9f9f9")
        self.Make.configure(anchor='w')
        self.Make.configure(compound='left')
        self.Make.configure(text='''Make''')

        self.Model = tk.Label(self.top)
        self.Model.place(x=280, y=158, height=27, width=109)
        self.Model.configure(activebackground="#f9f9f9")
        self.Model.configure(anchor='w')
        self.Model.configure(compound='left')
        self.Model.configure(text='''Model''')

        self.Year = tk.Label(self.top)
        self.Year.place(x=581, y=156, height=27, width=109)
        self.Year.configure(activebackground="#f9f9f9")
        self.Year.configure(anchor='w')
        self.Year.configure(compound='left')
        self.Year.configure(text='''Year''')

        self.Miles = tk.Label(self.top)
        self.Miles.place(x=280, y=190, height=27, width=109)
        self.Miles.configure(activebackground="#f9f9f9")
        self.Miles.configure(anchor='w')
        self.Miles.configure(compound='left')
        self.Miles.configure(text='''Miles''')

        self.Condition = tk.Label(self.top)
        self.Condition.place(x=580, y=190, height=27, width=109)
        self.Condition.configure(activebackground="#f9f9f9")
        self.Condition.configure(anchor='w')
        self.Condition.configure(compound='left')
        self.Condition.configure(text='''Condition''')

        self.Model_1_1_1_1 = tk.Label(self.top)
        self.Model_1_1_1_1.place(x=10, y=360, height=27, width=109)
        self.Model_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Model_1_1_1_1.configure(anchor='w')
        self.Model_1_1_1_1.configure(compound='left')
        self.Model_1_1_1_1.configure(text='''List Price''')

        self.SalesPrice = tk.Label(self.top)
        self.SalesPrice.place(x=10, y=400, height=27, width=109)
        self.SalesPrice.configure(activebackground="#f9f9f9")
        self.SalesPrice.configure(anchor='w')
        self.SalesPrice.configure(compound='left')
        self.SalesPrice.configure(text='''Sales Price''')

        self.Style = tk.Label(self.top)
        self.Style.place(x=10, y=236, height=27, width=109)
        self.Style.configure(activebackground="#f9f9f9")
        self.Style.configure(anchor='w')
        self.Style.configure(compound='left')
        self.Style.configure(text='''Style''')

        self.InteriorColor = tk.Label(self.top)
        self.InteriorColor.place(x=10, y=320, height=27, width=109)
        self.InteriorColor.configure(activebackground="#f9f9f9")
        self.InteriorColor.configure(anchor='w')
        self.InteriorColor.configure(compound='left')
        self.InteriorColor.configure(text='''Interior Color''')

        self.Vehicle1 = tk.Label(self.top)
        self.Vehicle1.place(x=10, y=120, height=27, width=130)
        self.Vehicle1.configure(activebackground="#f9f9f9")
        self.Vehicle1.configure(anchor='w')
        self.Vehicle1.configure(compound='left')
        self.Vehicle1.configure(highlightcolor="#ffffff")
        self.Vehicle1.configure(text='''Vehicle 1''')

        self.SellerDealer = tk.Label(self.top)
        self.SellerDealer.place(x=350, y=50, height=27, width=109)
        self.SellerDealer.configure(activebackground="#f9f9f9")
        self.SellerDealer.configure(anchor='w')
        self.SellerDealer.configure(compound='left')
        self.SellerDealer.configure(text='''Seller/Dealer''')

        self.TaxId = tk.Label(self.top)
        self.TaxId.place(x=350, y=90, height=27, width=109)
        self.TaxId.configure(activebackground="#f9f9f9")
        self.TaxId.configure(anchor='w')
        self.TaxId.configure(compound='left')
        self.TaxId.configure(text='''Tax ID''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(x=720, y=490, height=24, width=197)
        self.Button1.configure(command=CarPurchaseForm_support.AddVehicle)
        self.Button1.configure(compound='left')
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Add Vehicle''')

        self.Submit = tk.Button(self.top)
        self.Submit.place(x=750, y=680, height=24, width=177)
        self.Submit.configure(command=CarPurchaseForm_support.Submit)
        self.Submit.configure(compound='left')
        self.Submit.configure(pady="0")
        self.Submit.configure(text='''Submit''')

        self.DateEntry = tk.Entry(self.top)
        self.DateEntry.place(x=120, y=50, height=20, width=134)
        self.DateEntry.configure(background="white")
        self.DateEntry.configure(font="TkFixedFont")
        self.DateEntry.configure(selectbackground="blue")
        self.DateEntry.configure(selectforeground="white")
        self.DateEntry.configure(textvariable=self.dateValue)

        self.LocationEntry = tk.Entry(self.top)
        self.LocationEntry.place(x=120, y=90, height=20, width=134)
        self.LocationEntry.configure(background="white")
        self.LocationEntry.configure(font="TkFixedFont")
        self.LocationEntry.configure(selectbackground="blue")
        self.LocationEntry.configure(selectforeground="white")
        self.LocationEntry.configure(textvariable=self.locationValue)

        self.MakeEntry = tk.Entry(self.top)
        self.MakeEntry.place(x=120, y=160, height=20, width=134)
        self.MakeEntry.configure(background="white")
        self.MakeEntry.configure(font="TkFixedFont")
        self.MakeEntry.configure(selectbackground="blue")
        self.MakeEntry.configure(selectforeground="white")
        self.MakeEntry.configure(textvariable=self.makeValue)

        self.ModelEntry = tk.Entry(self.top)
        self.ModelEntry.place(x=410, y=160, height=20, width=134)
        self.ModelEntry.configure(background="white")
        self.ModelEntry.configure(font="TkFixedFont")
        self.ModelEntry.configure(selectbackground="blue")
        self.ModelEntry.configure(selectforeground="white")
        self.ModelEntry.configure(textvariable=self.modleValue)

        self.YearEntry = tk.Entry(self.top)
        self.YearEntry.place(x=700, y=160, height=20, width=134)
        self.YearEntry.configure(background="white")
        self.YearEntry.configure(font="TkFixedFont")
        self.YearEntry.configure(selectbackground="blue")
        self.YearEntry.configure(selectforeground="white")
        self.YearEntry.configure(textvariable=self.yearValue)

        self.MilesEntry = tk.Entry(self.top)
        self.MilesEntry.place(x=410, y=190, height=20, width=134)
        self.MilesEntry.configure(background="white")
        self.MilesEntry.configure(cursor="fleur")
        self.MilesEntry.configure(font="TkFixedFont")
        self.MilesEntry.configure(selectbackground="blue")
        self.MilesEntry.configure(selectforeground="white")
        self.MilesEntry.configure(textvariable=self.milesValue)

        self.ConditionEntry = tk.Entry(self.top)
        self.ConditionEntry.place(x=700, y=190, height=20, width=134)
        self.ConditionEntry.configure(background="white")
        self.ConditionEntry.configure(font="TkFixedFont")
        self.ConditionEntry.configure(selectbackground="blue")
        self.ConditionEntry.configure(selectforeground="white")
        self.ConditionEntry.configure(textvariable=self.conditionValue)

        self.ListEntry = tk.Entry(self.top)
        self.ListEntry.place(x=120, y=360, height=20, width=134)
        self.ListEntry.configure(background="white")
        self.ListEntry.configure(font="TkFixedFont")
        self.ListEntry.configure(selectbackground="blue")
        self.ListEntry.configure(selectforeground="white")
        self.ListEntry.configure(textvariable=self.listPriceValue)

        self.SalesPriceEntry = tk.Entry(self.top)
        self.SalesPriceEntry.place(x=120, y=400, height=20, width=134)
        self.SalesPriceEntry.configure(background="white")
        self.SalesPriceEntry.configure(font="TkFixedFont")
        self.SalesPriceEntry.configure(selectbackground="blue")
        self.SalesPriceEntry.configure(selectforeground="white")
        self.SalesPriceEntry.configure(textvariable=self.salePriceValue)

        self.StyleEntry = tk.Entry(self.top)
        self.StyleEntry.place(x=120, y=240, height=20, width=134)
        self.StyleEntry.configure(background="white")
        self.StyleEntry.configure(font="TkFixedFont")
        self.StyleEntry.configure(selectbackground="blue")
        self.StyleEntry.configure(selectforeground="white")
        self.StyleEntry.configure(textvariable=self.styleValue)

        self.InteriorColorEntry = tk.Entry(self.top)
        self.InteriorColorEntry.place(x=120, y=320, height=20, width=134)
        self.InteriorColorEntry.configure(background="white")
        self.InteriorColorEntry.configure(font="TkFixedFont")
        self.InteriorColorEntry.configure(selectbackground="blue")
        self.InteriorColorEntry.configure(selectforeground="white")
        self.InteriorColorEntry.configure(textvariable=self.interiorValue)

        self.SellerDealerEntry = tk.Entry(self.top)
        self.SellerDealerEntry.place(x=470, y=50, height=20, width=134)
        self.SellerDealerEntry.configure(background="white")
        self.SellerDealerEntry.configure(font="TkFixedFont")
        self.SellerDealerEntry.configure(selectbackground="blue")
        self.SellerDealerEntry.configure(selectforeground="white")
        self.SellerDealerEntry.configure(textvariable=self.sellerValue)

        self.TaxIDEntry = tk.Entry(self.top)
        self.TaxIDEntry.place(x=470, y=90, height=20, width=134)
        self.TaxIDEntry.configure(background="white")
        self.TaxIDEntry.configure(font="TkFixedFont")
        self.TaxIDEntry.configure(selectbackground="blue")
        self.TaxIDEntry.configure(selectforeground="white")
        self.TaxIDEntry.configure(textvariable=self.taxIDValue)

        self.Custom2 = CarPurchaseForm_support.Custom(self.top)
        self.Custom2.place(x=20, y=560, height=115, width=906)

        self.Custom3 = CarPurchaseForm_support.Custom(self.top)
        self.Custom3.place(x=270, y=260, height=135, width=646)

        self.TLabel1 = ttk.Label(self.top)
        self.TLabel1.place(x=270, y=240, height=25, width=177)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(anchor='w')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''Vehicle Problems''')
        self.TLabel1.configure(compound='left')

        self.TButton1 = ttk.Button(self.top)
        self.TButton1.place(x=790, y=420, height=34, width=119)
        self.TButton1.configure(command=CarPurchaseForm_support.randomData)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Random''')
        self.TButton1.configure(compound='left')

        self.VIN = tk.Label(self.top)
        self.VIN.place(x=10, y=200, height=27, width=109)
        self.VIN.configure(activebackground="#f9f9f9")
        self.VIN.configure(anchor='w')
        self.VIN.configure(compound='left')
        self.VIN.configure(text='''VIN''')

        self.VINEntry = tk.Entry(self.top)
        self.VINEntry.place(x=120, y=200, height=20, width=134)
        self.VINEntry.configure(background="white")
        self.VINEntry.configure(font="TkFixedFont")
        self.VINEntry.configure(selectbackground="blue")
        self.VINEntry.configure(selectforeground="white")
        self.VINEntry.configure(textvariable=self.vinValue)

        self.InteriorColor = tk.Label(self.top)
        self.InteriorColor.place(x=10, y=280, height=27, width=109)
        self.InteriorColor.configure(activebackground="#f9f9f9")
        self.InteriorColor.configure(anchor='w')
        self.InteriorColor.configure(compound='left')
        self.InteriorColor.configure(text='''Color''')

        self.ColorEntry = tk.Entry(self.top)
        self.ColorEntry.place(x=121, y=283, height=20, width=134)
        self.ColorEntry.configure(background="white")
        self.ColorEntry.configure(font="TkFixedFont")
        self.ColorEntry.configure(selectbackground="blue")
        self.ColorEntry.configure(selectforeground="white")
        self.ColorEntry.configure(textvariable=self.colorValue)

        self.SalesPrice = tk.Label(self.top)
        self.SalesPrice.place(x=10, y=440, height=27, width=109)
        self.SalesPrice.configure(activebackground="#f9f9f9")
        self.SalesPrice.configure(anchor='w')
        self.SalesPrice.configure(compound='left')
        self.SalesPrice.configure(cursor="fleur")
        self.SalesPrice.configure(text='''Book Value''')

        self.BookEntry = tk.Entry(self.top)
        self.BookEntry.place(x=122, y=442, height=20, width=134)
        self.BookEntry.configure(background="white")
        self.BookEntry.configure(cursor="fleur")
        self.BookEntry.configure(font="TkFixedFont")
        self.BookEntry.configure(selectbackground="blue")
        self.BookEntry.configure(selectforeground="white")
        self.BookEntry.configure(textvariable=self.bookValue)

        self.PricePaid = tk.Label(self.top)
        self.PricePaid.place(x=10, y=486, height=27, width=109)
        self.PricePaid.configure(activebackground="#f9f9f9")
        self.PricePaid.configure(anchor='w')
        self.PricePaid.configure(compound='left')
        self.PricePaid.configure(cursor="fleur")
        self.PricePaid.configure(text='''Price Paid''')
        self.PricePaid.configure(textvariable=self.pricePaidValue)
        self.pricePaidValue.set('''Price Paid''')

        self.BookEntry_1 = tk.Entry(self.top)
        self.BookEntry_1.place(x=130, y=490, height=20, width=134)
        self.BookEntry_1.configure(background="white")
        self.BookEntry_1.configure(font="TkFixedFont")
        self.BookEntry_1.configure(selectbackground="blue")
        self.BookEntry_1.configure(selectforeground="white")
        self.BookEntry_1.configure(textvariable=self.bookValue)

def start_up():
    CarPurchaseForm_support.main()

if __name__ == '__main__':
    CarPurchaseForm_support.main()




