#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 23, 2022 03:37:42 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 685x574+840+319
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "ListPrice" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Purchase 
    vTcl:DefineAlias "$top.lab46" "Purchase" vTcl:WidgetProc "ListPrice" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Date 
    vTcl:DefineAlias "$top.lab47" "Date" vTcl:WidgetProc "ListPrice" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Location 
    vTcl:DefineAlias "$top.lab48" "Location" vTcl:WidgetProc "ListPrice" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Make 
    vTcl:DefineAlias "$top.lab49" "Make" vTcl:WidgetProc "ListPrice" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Model 
    vTcl:DefineAlias "$top.lab50" "Model" vTcl:WidgetProc "ListPrice" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Year 
    vTcl:DefineAlias "$top.lab51" "Year" vTcl:WidgetProc "ListPrice" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Miles 
    vTcl:DefineAlias "$top.lab52" "Miles" vTcl:WidgetProc "ListPrice" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Condition 
    vTcl:DefineAlias "$top.lab53" "Condition" vTcl:WidgetProc "ListPrice" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {List Price} 
    vTcl:DefineAlias "$top.lab54" "Model_1_1_1_1" vTcl:WidgetProc "ListPrice" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Sales Price} 
    vTcl:DefineAlias "$top.lab55" "SalesPrice" vTcl:WidgetProc "ListPrice" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Style 
    vTcl:DefineAlias "$top.lab56" "Style" vTcl:WidgetProc "ListPrice" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Interior Color} 
    vTcl:DefineAlias "$top.lab57" "InteriorColor" vTcl:WidgetProc "ListPrice" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor #ffffff \
        -text {Vehicle 1} 
    vTcl:DefineAlias "$top.lab58" "Vehicle1" vTcl:WidgetProc "ListPrice" 1
    label $top.lab70 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Seller/Dealer 
    vTcl:DefineAlias "$top.lab70" "SellerDealer" vTcl:WidgetProc "ListPrice" 1
    label $top.lab71 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Tax ID} 
    vTcl:DefineAlias "$top.lab71" "TaxId" vTcl:WidgetProc "ListPrice" 1
    button $top.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command AddVehicle -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add Vehicle} 
    vTcl:DefineAlias "$top.but74" "Button1" vTcl:WidgetProc "ListPrice" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command Submit -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but75" "Submit" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent76 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent76" "DateEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent46" "LocationEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent47" "MakeEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent48" "ModelEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent49" "YearEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent50" "MilesEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent51" "ConditionEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent52" "ListEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent53" "SalesPriceEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent54" "StyleEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent55" "InteriorColorEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent56" "SellerDealerEntry" vTcl:WidgetProc "ListPrice" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$top.ent57" "TaxIDEntry" vTcl:WidgetProc "ListPrice" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.087 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.157 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.279 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.348 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.418 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.488 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.557 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.627 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.697 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.767 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.836 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.209 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.511 -y 0 -rely 0.087 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.511 -y 0 -rely 0.157 -width 0 -relwidth 0.159 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.923 -width 197 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.642 -y 0 -rely 0.923 -width 177 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.087 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.157 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.279 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.348 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.418 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.488 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.557 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.627 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.697 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.767 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.175 -y 0 -rely 0.836 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.686 -y 0 -rely 0.087 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.686 -y 0 -rely 0.157 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

