#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2022 03:37:45 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import CarPurchaseForm

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = CarPurchaseForm.ListPrice(_top1)
    root.mainloop()

def AddVehicle(*args):
    print('CarPurchaseForm_support.AddVehicle')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Submit(*args):
    print('CarPurchaseForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    CarPurchaseForm.start_up()




