#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 15, 2022 07:25:53 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m53" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+775+219
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1796 1101
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {First Name:} 
    vTcl:DefineAlias "$top.lab46" "FirstName" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Address: 
    vTcl:DefineAlias "$top.lab47" "Address" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text State: 
    vTcl:DefineAlias "$top.lab48" "State" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text DOB: 
    vTcl:DefineAlias "$top.lab49" "DOB" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Gender: 
    vTcl:DefineAlias "$top.lab50" "Gender" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex51 \
        -background white -font TkTextFont -foreground black -height 24 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex51 configure -font "TkTextFont"
    $top.tex51 insert end text
    vTcl:DefineAlias "$top.tex51" "FirstNameText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex52 configure -font "TkTextFont"
    $top.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "AddressText" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m53 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    text $top.tex54 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex54 configure -font "TkTextFont"
    $top.tex54 insert end text
    vTcl:DefineAlias "$top.tex54" "StateText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex55 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex55 configure -font "TkTextFont"
    $top.tex55 insert end text
    vTcl:DefineAlias "$top.tex55" "DOBText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex56 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex56 configure -font "TkTextFont"
    $top.tex56 insert end text
    vTcl:DefineAlias "$top.tex56" "GenderText" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Last Name:} 
    vTcl:DefineAlias "$top.lab57" "LastName" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text City: 
    vTcl:DefineAlias "$top.lab58" "City" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Zip: 
    vTcl:DefineAlias "$top.lab59" "Zip" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Tax ID:} 
    vTcl:DefineAlias "$top.lab60" "TaxID" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Phone: 
    vTcl:DefineAlias "$top.lab61" "Phone" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex62 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex62 configure -font "TkTextFont"
    $top.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "LastNameText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex63 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex63 configure -font "TkTextFont"
    $top.tex63 insert end text
    vTcl:DefineAlias "$top.tex63" "CityText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex64 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex64 configure -font "TkTextFont"
    $top.tex64 insert end text
    vTcl:DefineAlias "$top.tex64" "ZipText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex65 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex65 configure -font "TkTextFont"
    $top.tex65 insert end text
    vTcl:DefineAlias "$top.tex65" "TaxIDText" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex66 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 -wrap word 
    $top.tex66 configure -font "TkTextFont"
    $top.tex66 insert end text
    vTcl:DefineAlias "$top.tex66" "PhoneText" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Select Customer:} 
    vTcl:DefineAlias "$top.lab67" "SelectCustomer" vTcl:WidgetProc "Toplevel1" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command Search -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$top.but68" "Search" vTcl:WidgetProc "Toplevel1" 1
    button $top.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command AddNewCustomer \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add New Customer} 
    vTcl:DefineAlias "$top.but69" "AddNewCustomer" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -y 0 -rely 0.133 -width 0 -relwidth 0.14 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -y 0 -rely 0.267 -width 0 -relwidth 0.14 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -y 0 -rely 0.4 -width 0 -relwidth 0.14 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -y 0 -rely 0.556 -width 0 -relwidth 0.14 -height 0 \
        -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -y 0 -rely 0.667 -width 0 -relwidth 0.14 -height 0 \
        -relheight 0.091 -anchor nw -bordermode ignore 
    place $top.tex51 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.133 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.267 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex54 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.4 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex55 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.533 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex56 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.689 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.133 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.267 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.4 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.533 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.5 -y 0 -rely 0.689 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.133 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex63 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.267 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex64 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.4 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex65 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.533 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.tex66 \
        -in $top -x 0 -relx 0.65 -y 0 -rely 0.689 -width 0 -relwidth 0.273 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.167 -y 0 -rely 0.867 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.533 -y 0 -rely 0.867 -width 187 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

