#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2022 07:25:54 PM PDT  platform: Windows NT
#    Apr 27, 2022 10:54:56 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

from database.customer import Customer
from database.database import Database
from ui.CustomerADDorSelectForm import CustomerADDorSelectForm

customer = None


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    # _w1 = CustomerADDorSelectForm.Toplevel1(_top1)
    _w1 = CustomerADDorSelectForm.SelectCustomerForm(_top1)
    root.mainloop()


def AddNewCustomer(*args):
    print('CustomerADDorSelectForm_support.AddNewCustomer')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()
    global customer
    global callback
    customer = Customer(0,
                        _w1.PhoneText.get("1.0", "end-1c"),
                        _w1.LastNameText.get("1.0", "end-1c"),
                        _w1.FirstNameText.get("1.0", "end-1c"),
                        _w1.AddressText.get("1.0", "end-1c"),
                        _w1.CityText.get("1.0", "end-1c"),
                        _w1.StateText.get("1.0", "end-1c"),
                        _w1.ZipText.get("1.0", "end-1c"),
                        _w1.GenderText.get("1.0", "end-1c"),
                        _w1.DOBText.get("1.0", "end-1c"),
                        _w1.TaxIDText.get("1.0", "end-1c"),
                        )
    callback(customer)
    root.destroy()

def Search(*args):
    print('CustomerADDorSelectForm_support.Search')
    for arg in args:
        print('another arg:', arg)
    sys.stdout.flush()

    db = Database()
    results = db.searchCustomers(customer_last_name=_w1.LastNameText.get("1.0", "end-1c"),
                                 customer_first_name=_w1.FirstNameText.get("1.0", "end-1c"),
                                 customer_taxpayer_id=_w1.TaxIDText.get("1.0", "end-1c"))

    if len(results) > 0:
        print(results[0])
    if results is not None and len(results) == 1:
        global customer
        customer = results[0]
        _w1.PhoneText.delete("1.0", "end-1c")
        _w1.LastNameText.delete("1.0", "end-1c")
        _w1.FirstNameText.delete("1.0", "end-1c")
        _w1.AddressText.delete("1.0", "end-1c")
        _w1.CityText.delete("1.0", "end-1c")
        _w1.StateText.delete("1.0", "end-1c")
        _w1.ZipText.delete("1.0", "end-1c")
        _w1.GenderText.delete("1.0", "end-1c")
        _w1.DOBText.delete("1.0", "end-1c")
        _w1.TaxIDText.delete("1.0", "end-1c")
        _w1.PhoneText.delete("1.0", "end-1c")
        _w1.LastNameText.insert("1.0", customer.customer_last_name)
        _w1.FirstNameText.insert("1.0",customer.customer_first_name)
        _w1.AddressText.insert("1.0",customer.customer_address)
        _w1.CityText.insert("1.0",customer.customer_city)
        _w1.StateText.insert("1.0",customer.customer_state)
        _w1.ZipText.insert("1.0",customer.customer_zip)
        _w1.GenderText.insert("1.0",customer.customer_gender)
        _w1.DOBText.insert("1.0",customer.customer_dob)
        _w1.TaxIDText.insert("1.0",customer.customer_taxpayer_id)
        _w1.PhoneText.insert("1.0",customer.customer_phone)

callback = None
def selectCustomer(customerCallback):
    global callback
    callback = customerCallback
    CustomerADDorSelectForm.start_up()

if __name__ == '__main__':
    CustomerADDorSelectForm.start_up()
