#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2022 07:25:54 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import CustomerADDorSelectForm

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = CustomerADDorSelectForm.Toplevel1(_top1)
    root.mainloop()

def AddNewCustomer(*args):
    print('CustomerADDorSelectForm_support.AddNewCustomer')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Search(*args):
    print('CustomerADDorSelectForm_support.Search')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    CustomerADDorSelectForm.start_up()




