#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 27, 2022 01:04:17 PM PDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 715x539+2655+704
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Vehicle Sale"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "VehicleSaleForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Sale 
    vTcl:DefineAlias "$top.lab46" "Sale" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Date 
    vTcl:DefineAlias "$top.lab47" "Date" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Total Due} 
    vTcl:DefineAlias "$top.lab48" "TotalDue" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Down Payment} 
    vTcl:DefineAlias "$top.lab49" "DownPayment" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Financed Amount} 
    vTcl:DefineAlias "$top.lab50" "FinancedAmount" vTcl:WidgetProc "VehicleSaleForm" 1
    entry $top.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable dateValue -width 154 
    vTcl:DefineAlias "$top.ent51" "DateEntry" vTcl:WidgetProc "VehicleSaleForm" 1
    entry $top.ent52 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable totalDueValue -width 154 
    vTcl:DefineAlias "$top.ent52" "TotalDueEntry" vTcl:WidgetProc "VehicleSaleForm" 1
    entry $top.ent53 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable downPaymentValue -width 154 
    vTcl:DefineAlias "$top.ent53" "DownPaymentEntry" vTcl:WidgetProc "VehicleSaleForm" 1
    entry $top.ent54 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable financedAmount -width 154 
    vTcl:DefineAlias "$top.ent54" "FinancedAmountEntry" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Salesperson 
    vTcl:DefineAlias "$top.lab55" "Salesperson" vTcl:WidgetProc "VehicleSaleForm" 1
    entry $top.ent56 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable commissionValue -width 154 
    vTcl:DefineAlias "$top.ent56" "CommissionEntry" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Commission 
    vTcl:DefineAlias "$top.lab57" "Commission" vTcl:WidgetProc "VehicleSaleForm" 1
    spinbox $top.spi58 \
        -activebackground #f9f9f9 -background white -command SalespersonNames \
        -font TkDefaultFont -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -to 100.0 \
        -values {Salesperson1 Salesperson2 Salesperson3 Salesperson4} 
    vTcl:DefineAlias "$top.spi58" "SalespersonSpinbox" vTcl:WidgetProc "VehicleSaleForm" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Customer 
    vTcl:DefineAlias "$top.lab59" "Customer" vTcl:WidgetProc "VehicleSaleForm" 1
    text $top.tex60 \
        -background white -font TkTextFont -foreground black -height 74 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 -wrap word 
    $top.tex60 configure -font "TkTextFont"
    $top.tex60 insert end text
    vTcl:DefineAlias "$top.tex60" "CustomerDetailsText" vTcl:WidgetProc "VehicleSaleForm" 1
    button $top.but61 \
        -background $vTcl(actual_gui_bg) -command SelectCustomer \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Select Customer} 
    vTcl:DefineAlias "$top.but61" "SelectCustomer" vTcl:WidgetProc "VehicleSaleForm" 1
    text $top.tex62 \
        -background white -font TkTextFont -foreground black -height 94 \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 -wrap word 
    $top.tex62 configure -font "TkTextFont"
    $top.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "CarDetailsText" vTcl:WidgetProc "VehicleSaleForm" 1
    button $top.but63 \
        -background $vTcl(actual_gui_bg) -command SelectVehicle \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Select Vehicle} 
    vTcl:DefineAlias "$top.but63" "SelectVehicle" vTcl:WidgetProc "VehicleSaleForm" 1
    button $top.but64 \
        -background $vTcl(actual_gui_bg) -command Submit -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but64" "Submit" vTcl:WidgetProc "VehicleSaleForm" 1
    button $top.but66 \
        -background $vTcl(actual_gui_bg) -command AddWorkHistory \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -pady 0 -text {Add Work History} 
    vTcl:DefineAlias "$top.but66" "AddWorkHistory" vTcl:WidgetProc "VehicleSaleForm" 1
    text $top.tex51 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 433 -wrap word 
    $top.tex51 configure -font "TkTextFont"
    $top.tex51 insert end text
    vTcl:DefineAlias "$top.tex51" "WorkHistory" vTcl:WidgetProc "VehicleSaleForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.019 -width 0 -relwidth 0.207 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.093 -width 0 -relwidth 0.174 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.186 -width 0 -relwidth 0.174 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.278 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.371 -width 0 -relwidth 0.174 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.093 -width 154 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.186 -width 154 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.278 -width 154 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.371 -width 154 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.093 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.696 -y 0 -rely 0.186 -width 154 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.186 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.spi58 \
        -in $top -x 0 -relx 0.696 -y 0 -rely 0.093 -width 0 -relwidth 0.245 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.445 -width 0 -relwidth 0.158 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.tex60 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.501 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.137 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.649 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.724 -width 0 -relwidth 0.228 \
        -height 0 -relheight 0.174 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.032 -y 0 -rely 0.909 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.706 -y 0 -rely 0.913 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.38 -y 0 -rely 0.649 -width 147 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex51 \
        -in $top -x 0 -relx 0.378 -y 0 -rely 0.501 -width 0 -relwidth 0.606 \
        -height 0 -relheight 0.137 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m67" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+1125+380
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m67 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

