#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 25, 2022 08:05:00 AM PDT  platform: Windows NT
#    Apr 27, 2022 10:40:15 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import CarSaleForm
import ui
from ui import CustomerADDorSelectForm
from ui.AddCustomerEmployerForm import AddCustomerEmployerForm
from ui.AddCustomerEmployerForm import AddCustomerEmployerForm_support
from ui.CustomerADDorSelectForm import CustomerADDorSelectForm_support

employment_history = []

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    # _w1 = CarSaleForm.Toplevel1(_top1)
    _w1 = CarSaleForm.VehicleSaleForm(_top1)
    root.mainloop()

def AddWorkHistory(*args):
    print('CarSaleForm_support.AddWorkHistory')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()
    AddCustomerEmployerForm_support.addEmployer(addEmployer)

def addEmployer(employment):
    employment_history.append(employment)

def SalespersonNames(*args):
    print('CarSaleForm_support.SalespersonNames')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def SelectCustomer(*args):
    print('CarSaleForm_support.SelectCustomer')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()
    CustomerADDorSelectForm_support.selectCustomer(customerSelected)

def customerSelected(customer):
    print("customer selected:", customer)
    _w1.CustomerDetailsText.insert("1.0", customer.getText())
    pass

def SelectVehicle(*args):
    print('CarSaleForm_support.SelectVehicle')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def Submit(*args):
    print('CarSaleForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    CarSaleForm.start_up()





