#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 30, 2022 08:16:26 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import AddCustomerPaymentForm

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = AddCustomerPaymentForm.AddCustomerPaymentForm(_top1)
    root.mainloop()

def Submit(*args):
    print('AddCustomerPaymentForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

Custom = tk.Frame  # To be updated by user with name of custom widget.

if __name__ == '__main__':
    AddCustomerPaymentForm.start_up()




