#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 30, 2022 08:16:24 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+913+323
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Add Customer Payment Form"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "AddCustomerPaymentForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Select a customer to enter payments:} 
    vTcl:DefineAlias "$top.lab46" "SelectACustomer" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Customer 
    vTcl:DefineAlias "$top.lab47" "Customer" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 144 
    vTcl:DefineAlias "$top.ent48" "Entry1" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command Submit -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Submit 
    vTcl:DefineAlias "$top.but49" "Submit" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Payment History} 
    vTcl:DefineAlias "$top.lab51" "Label1" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Payment Date} 
    vTcl:DefineAlias "$top.lab53" "PaymentDate" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Due 
    vTcl:DefineAlias "$top.lab54" "Due" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Paid Date} 
    vTcl:DefineAlias "$top.lab55" "PaidDate" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Amount 
    vTcl:DefineAlias "$top.lab56" "Amount" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Bank Amount} 
    vTcl:DefineAlias "$top.lab57" "BankAmount" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add More} 
    vTcl:DefineAlias "$top.but63" "AddMore" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent64 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent64" "PaymentDateEntry" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent65 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent65" "DueEntry" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent66 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent66" "PaidDateEntry" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent67 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent67" "AmountEntry" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    entry $top.ent68 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent68" "BankAmountEntry" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    vTcl::widgets::ttk::custom::CreateCmd $top.cus69 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.cus69" "Custom1" vTcl:WidgetProc "AddCustomerPaymentForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.44 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.111 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.111 -width 144 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.533 -y 0 -rely 0.111 -width 107 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.222 -width 0 -relwidth 0.29 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.489 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.489 -width 0 -relwidth 0.09 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.489 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.489 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.489 -width 0 -relwidth 0.157 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.417 -y 0 -rely 0.911 -width 127 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.556 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent65 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.556 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent66 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.556 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent67 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.556 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent68 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.556 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.cus69 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.311 -width 0 -relwidth 0.873 \
        -height 0 -relheight 0.109 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

