#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 30, 2022 08:16:33 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import AddCustomerPaymentForm_support

class AddCustomerPaymentForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+913+323")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Add Customer Payment Form")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.SelectACustomer = tk.Label(self.top)
        self.SelectACustomer.place(relx=0.017, rely=0.022, height=21, width=264)
        self.SelectACustomer.configure(activebackground="#f9f9f9")
        self.SelectACustomer.configure(activeforeground="black")
        self.SelectACustomer.configure(anchor='w')
        self.SelectACustomer.configure(background="#d9d9d9")
        self.SelectACustomer.configure(compound='left')
        self.SelectACustomer.configure(disabledforeground="#a3a3a3")
        self.SelectACustomer.configure(foreground="#000000")
        self.SelectACustomer.configure(highlightbackground="#d9d9d9")
        self.SelectACustomer.configure(highlightcolor="black")
        self.SelectACustomer.configure(text='''Select a customer to enter payments:''')

        self.Customer = tk.Label(self.top)
        self.Customer.place(relx=0.033, rely=0.111, height=21, width=94)
        self.Customer.configure(activebackground="#f9f9f9")
        self.Customer.configure(activeforeground="black")
        self.Customer.configure(anchor='w')
        self.Customer.configure(background="#d9d9d9")
        self.Customer.configure(compound='left')
        self.Customer.configure(disabledforeground="#a3a3a3")
        self.Customer.configure(foreground="#000000")
        self.Customer.configure(highlightbackground="#d9d9d9")
        self.Customer.configure(highlightcolor="black")
        self.Customer.configure(text='''Customer''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(relx=0.2, rely=0.111, height=20, relwidth=0.24)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")

        self.Submit = tk.Button(self.top)
        self.Submit.place(relx=0.533, rely=0.111, height=24, width=107)
        self.Submit.configure(activebackground="#ececec")
        self.Submit.configure(activeforeground="#000000")
        self.Submit.configure(background="#d9d9d9")
        self.Submit.configure(command=AddCustomerPaymentForm_support.Submit)
        self.Submit.configure(compound='left')
        self.Submit.configure(disabledforeground="#a3a3a3")
        self.Submit.configure(foreground="#000000")
        self.Submit.configure(highlightbackground="#d9d9d9")
        self.Submit.configure(highlightcolor="black")
        self.Submit.configure(pady="0")
        self.Submit.configure(text='''Submit''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.017, rely=0.222, height=21, width=174)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Payment History''')

        self.PaymentDate = tk.Label(self.top)
        self.PaymentDate.place(relx=0.067, rely=0.489, height=21, width=94)
        self.PaymentDate.configure(activebackground="#f9f9f9")
        self.PaymentDate.configure(activeforeground="black")
        self.PaymentDate.configure(anchor='w')
        self.PaymentDate.configure(background="#d9d9d9")
        self.PaymentDate.configure(compound='left')
        self.PaymentDate.configure(disabledforeground="#a3a3a3")
        self.PaymentDate.configure(foreground="#000000")
        self.PaymentDate.configure(highlightbackground="#d9d9d9")
        self.PaymentDate.configure(highlightcolor="black")
        self.PaymentDate.configure(text='''Payment Date''')

        self.Due = tk.Label(self.top)
        self.Due.place(relx=0.283, rely=0.489, height=21, width=54)
        self.Due.configure(activebackground="#f9f9f9")
        self.Due.configure(activeforeground="black")
        self.Due.configure(anchor='w')
        self.Due.configure(background="#d9d9d9")
        self.Due.configure(compound='left')
        self.Due.configure(disabledforeground="#a3a3a3")
        self.Due.configure(foreground="#000000")
        self.Due.configure(highlightbackground="#d9d9d9")
        self.Due.configure(highlightcolor="black")
        self.Due.configure(text='''Due''')

        self.PaidDate = tk.Label(self.top)
        self.PaidDate.place(relx=0.45, rely=0.489, height=21, width=94)
        self.PaidDate.configure(activebackground="#f9f9f9")
        self.PaidDate.configure(activeforeground="black")
        self.PaidDate.configure(anchor='w')
        self.PaidDate.configure(background="#d9d9d9")
        self.PaidDate.configure(compound='left')
        self.PaidDate.configure(disabledforeground="#a3a3a3")
        self.PaidDate.configure(foreground="#000000")
        self.PaidDate.configure(highlightbackground="#d9d9d9")
        self.PaidDate.configure(highlightcolor="black")
        self.PaidDate.configure(text='''Paid Date''')

        self.Amount = tk.Label(self.top)
        self.Amount.place(relx=0.633, rely=0.489, height=21, width=94)
        self.Amount.configure(activebackground="#f9f9f9")
        self.Amount.configure(activeforeground="black")
        self.Amount.configure(anchor='w')
        self.Amount.configure(background="#d9d9d9")
        self.Amount.configure(compound='left')
        self.Amount.configure(disabledforeground="#a3a3a3")
        self.Amount.configure(foreground="#000000")
        self.Amount.configure(highlightbackground="#d9d9d9")
        self.Amount.configure(highlightcolor="black")
        self.Amount.configure(text='''Amount''')

        self.BankAmount = tk.Label(self.top)
        self.BankAmount.place(relx=0.783, rely=0.489, height=21, width=94)
        self.BankAmount.configure(activebackground="#f9f9f9")
        self.BankAmount.configure(activeforeground="black")
        self.BankAmount.configure(anchor='w')
        self.BankAmount.configure(background="#d9d9d9")
        self.BankAmount.configure(compound='left')
        self.BankAmount.configure(disabledforeground="#a3a3a3")
        self.BankAmount.configure(foreground="#000000")
        self.BankAmount.configure(highlightbackground="#d9d9d9")
        self.BankAmount.configure(highlightcolor="black")
        self.BankAmount.configure(text='''Bank Amount''')

        self.AddMore = tk.Button(self.top)
        self.AddMore.place(relx=0.417, rely=0.911, height=24, width=127)
        self.AddMore.configure(activebackground="#ececec")
        self.AddMore.configure(activeforeground="#000000")
        self.AddMore.configure(background="#d9d9d9")
        self.AddMore.configure(compound='left')
        self.AddMore.configure(disabledforeground="#a3a3a3")
        self.AddMore.configure(foreground="#000000")
        self.AddMore.configure(highlightbackground="#d9d9d9")
        self.AddMore.configure(highlightcolor="black")
        self.AddMore.configure(pady="0")
        self.AddMore.configure(text='''Add More''')

        self.PaymentDateEntry = tk.Entry(self.top)
        self.PaymentDateEntry.place(relx=0.067, rely=0.556, height=20
                , relwidth=0.14)
        self.PaymentDateEntry.configure(background="white")
        self.PaymentDateEntry.configure(disabledforeground="#a3a3a3")
        self.PaymentDateEntry.configure(font="TkFixedFont")
        self.PaymentDateEntry.configure(foreground="#000000")
        self.PaymentDateEntry.configure(highlightbackground="#d9d9d9")
        self.PaymentDateEntry.configure(highlightcolor="black")
        self.PaymentDateEntry.configure(insertbackground="black")
        self.PaymentDateEntry.configure(selectbackground="blue")
        self.PaymentDateEntry.configure(selectforeground="white")

        self.DueEntry = tk.Entry(self.top)
        self.DueEntry.place(relx=0.25, rely=0.556, height=20, relwidth=0.14)
        self.DueEntry.configure(background="white")
        self.DueEntry.configure(disabledforeground="#a3a3a3")
        self.DueEntry.configure(font="TkFixedFont")
        self.DueEntry.configure(foreground="#000000")
        self.DueEntry.configure(highlightbackground="#d9d9d9")
        self.DueEntry.configure(highlightcolor="black")
        self.DueEntry.configure(insertbackground="black")
        self.DueEntry.configure(selectbackground="blue")
        self.DueEntry.configure(selectforeground="white")

        self.PaidDateEntry = tk.Entry(self.top)
        self.PaidDateEntry.place(relx=0.433, rely=0.556, height=20
                , relwidth=0.14)
        self.PaidDateEntry.configure(background="white")
        self.PaidDateEntry.configure(disabledforeground="#a3a3a3")
        self.PaidDateEntry.configure(font="TkFixedFont")
        self.PaidDateEntry.configure(foreground="#000000")
        self.PaidDateEntry.configure(highlightbackground="#d9d9d9")
        self.PaidDateEntry.configure(highlightcolor="black")
        self.PaidDateEntry.configure(insertbackground="black")
        self.PaidDateEntry.configure(selectbackground="blue")
        self.PaidDateEntry.configure(selectforeground="white")

        self.AmountEntry = tk.Entry(self.top)
        self.AmountEntry.place(relx=0.617, rely=0.556, height=20, relwidth=0.14)
        self.AmountEntry.configure(background="white")
        self.AmountEntry.configure(disabledforeground="#a3a3a3")
        self.AmountEntry.configure(font="TkFixedFont")
        self.AmountEntry.configure(foreground="#000000")
        self.AmountEntry.configure(highlightbackground="#d9d9d9")
        self.AmountEntry.configure(highlightcolor="black")
        self.AmountEntry.configure(insertbackground="black")
        self.AmountEntry.configure(selectbackground="blue")
        self.AmountEntry.configure(selectforeground="white")

        self.BankAmountEntry = tk.Entry(self.top)
        self.BankAmountEntry.place(relx=0.783, rely=0.556, height=20
                , relwidth=0.14)
        self.BankAmountEntry.configure(background="white")
        self.BankAmountEntry.configure(disabledforeground="#a3a3a3")
        self.BankAmountEntry.configure(font="TkFixedFont")
        self.BankAmountEntry.configure(foreground="#000000")
        self.BankAmountEntry.configure(highlightbackground="#d9d9d9")
        self.BankAmountEntry.configure(highlightcolor="black")
        self.BankAmountEntry.configure(insertbackground="black")
        self.BankAmountEntry.configure(selectbackground="blue")
        self.BankAmountEntry.configure(selectforeground="white")

        self.Custom1 = AddCustomerPaymentForm_support.Custom(self.top)
        self.Custom1.place(relx=0.067, rely=0.311, relheight=0.109
                , relwidth=0.873)

def start_up():
    AddCustomerPaymentForm_support.main()

if __name__ == '__main__':
    AddCustomerPaymentForm_support.main()




