#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 01, 2022 03:18:56 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import AddCustomerPaymentForm_support

class AddCustomerPaymentForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("792x757+983+931")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0,  0)
        top.title("Add Customer Payment Form")
        top.configure(highlightcolor="black")

        self.top = top
        self.paymentDueValue = tk.StringVar()
        self.amountDueValue = tk.StringVar()
        self.paidDateValue = tk.StringVar()
        self.amuntPaidValue = tk.StringVar()
        self.bankAccountValue = tk.StringVar()
        self.customerValue = tk.StringVar()

        self.SelectACustomer = tk.Label(self.top)
        self.SelectACustomer.place(x=11, y=14, height=28, width=426)
        self.SelectACustomer.configure(activebackground="#f9f9f9")
        self.SelectACustomer.configure(anchor='w')
        self.SelectACustomer.configure(compound='left')
        self.SelectACustomer.configure(text='''Select a customer to enter payments:''')

        self.Customer = tk.Label(self.top)
        self.Customer.place(x=20, y=60, height=29, width=105)
        self.Customer.configure(activebackground="#f9f9f9")
        self.Customer.configure(anchor='w')
        self.Customer.configure(compound='left')
        self.Customer.configure(text='''Customer''')

        self.Entry1 = tk.Entry(self.top)
        self.Entry1.place(x=477, y=54, height=20, width=144)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="blue")
        self.Entry1.configure(selectforeground="white")

        self.Submit = tk.Button(self.top)
        self.Submit.place(x=654, y=54, height=24, width=107)
        self.Submit.configure(command=AddCustomerPaymentForm_support.Submit)
        self.Submit.configure(compound='left')
        self.Submit.configure(pady="0")
        self.Submit.configure(text='''Submit''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(x=0, y=259, height=29, width=193)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.Label1.configure(text='''Payment History''')

        self.PaymentDate = tk.Label(self.top)
        self.PaymentDate.place(x=10, y=150, height=28, width=145)
        self.PaymentDate.configure(activebackground="#f9f9f9")
        self.PaymentDate.configure(anchor='w')
        self.PaymentDate.configure(compound='left')
        self.PaymentDate.configure(text='''Payment Date''')

        self.Due = tk.Label(self.top)
        self.Due.place(x=180, y=150, height=28, width=111)
        self.Due.configure(activebackground="#f9f9f9")
        self.Due.configure(anchor='w')
        self.Due.configure(compound='left')
        self.Due.configure(text='''Amount Due''')

        self.PaidDate = tk.Label(self.top)
        self.PaidDate.place(x=290, y=140, height=28, width=105)
        self.PaidDate.configure(activebackground="#f9f9f9")
        self.PaidDate.configure(anchor='w')
        self.PaidDate.configure(compound='left')
        self.PaidDate.configure(text='''Paid Date''')

        self.Amount = tk.Label(self.top)
        self.Amount.place(x=430, y=140, height=28, width=105)
        self.Amount.configure(activebackground="#f9f9f9")
        self.Amount.configure(anchor='w')
        self.Amount.configure(compound='left')
        self.Amount.configure(text='''Amount''')

        self.BankAmount = tk.Label(self.top)
        self.BankAmount.place(x=540, y=140, height=28, width=105)
        self.BankAmount.configure(activebackground="#f9f9f9")
        self.BankAmount.configure(anchor='w')
        self.BankAmount.configure(compound='left')
        self.BankAmount.configure(text='''Bank Account''')

        self.AddMore = tk.Button(self.top)
        self.AddMore.place(x=680, y=180, height=34, width=107)
        self.AddMore.configure(command=AddCustomerPaymentForm_support.AddPayment)
        self.AddMore.configure(compound='left')
        self.AddMore.configure(pady="0")
        self.AddMore.configure(text='''Add''')

        self.PaymentDateEntry = tk.Entry(self.top)
        self.PaymentDateEntry.place(x=10, y=180, height=30, width=134)
        self.PaymentDateEntry.configure(background="white")
        self.PaymentDateEntry.configure(font="TkFixedFont")
        self.PaymentDateEntry.configure(selectbackground="blue")
        self.PaymentDateEntry.configure(selectforeground="white")
        self.PaymentDateEntry.configure(textvariable=self.paymentDueValue)

        self.DueEntry = tk.Entry(self.top)
        self.DueEntry.place(x=170, y=180, height=30, width=104)
        self.DueEntry.configure(background="white")
        self.DueEntry.configure(font="TkFixedFont")
        self.DueEntry.configure(selectbackground="blue")
        self.DueEntry.configure(selectforeground="white")
        self.DueEntry.configure(textvariable=self.amountDueValue)

        self.PaidDateEntry = tk.Entry(self.top)
        self.PaidDateEntry.place(x=290, y=180, height=30, width=124)
        self.PaidDateEntry.configure(background="white")
        self.PaidDateEntry.configure(font="TkFixedFont")
        self.PaidDateEntry.configure(selectbackground="blue")
        self.PaidDateEntry.configure(selectforeground="white")
        self.PaidDateEntry.configure(textvariable=self.paidDateValue)

        self.AmountEntry = tk.Entry(self.top)
        self.AmountEntry.place(x=430, y=180, height=30, width=94)
        self.AmountEntry.configure(background="white")
        self.AmountEntry.configure(font="TkFixedFont")
        self.AmountEntry.configure(selectbackground="blue")
        self.AmountEntry.configure(selectforeground="white")
        self.AmountEntry.configure(textvariable=self.amuntPaidValue)

        self.BankAmountEntry = tk.Entry(self.top)
        self.BankAmountEntry.place(x=540, y=180, height=30, width=114)
        self.BankAmountEntry.configure(background="white")
        self.BankAmountEntry.configure(font="TkFixedFont")
        self.BankAmountEntry.configure(selectbackground="blue")
        self.BankAmountEntry.configure(selectforeground="white")
        self.BankAmountEntry.configure(textvariable=self.bankAccountValue)

        self.Custom1 = AddCustomerPaymentForm_support.Custom(self.top)
        self.Custom1.place(x=11, y=459, height=288, width=770)

        self.CustomerComboBox = ttk.Combobox(self.top)
        self.CustomerComboBox.place(x=144, y=54, height=36, width=285)
        self.CustomerComboBox.configure(textvariable=self.customerValue)
        self.CustomerComboBox.configure(takefocus="")

        self.Custom4 = AddCustomerPaymentForm_support.CustomHtmlLabel(self.top)
        self.Custom4.place(x=11, y=285, height=156, width=771)

        self.TSeparator3 = ttk.Separator(self.top)
        self.TSeparator3.place(x=10, y=110, width=770)

        self.TLabel4 = ttk.Label(self.top)
        self.TLabel4.place(x=10, y=120, height=25, width=248)
        self.TLabel4.configure(background="#d9d9d9")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font="-family {DejaVu Sans} -size 10 -weight bold")
        self.TLabel4.configure(relief="flat")
        self.TLabel4.configure(anchor='w')
        self.TLabel4.configure(justify='left')
        self.TLabel4.configure(text='''Add Customer Payment''')
        self.TLabel4.configure(compound='left')

def start_up():
    AddCustomerPaymentForm_support.main()

if __name__ == '__main__':
    AddCustomerPaymentForm_support.main()




