#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 23, 2022 10:02:21 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from random import random
from tkinter.constants import *

import tkhtmlview

from database.database import Database
import random

from ui.generic_report import generic_report
from ui.generic_report.generic_report import HtmlWindow

html = ""
title = "Report"

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = HtmlWindow(_top1)
    global html
    global title
    if len(html) == 0:
        db = Database()
        report = db.getSaleReport(8)
        html = report.getHtml()
        title = "Sales Report"
    _w1.Custom1.set_html(html)
    db.close()
    _w1.top.title = title
    root.mainloop()

def start(*args):
    '''Main entry point for the application.'''
    global topLevel
    topLevel = tk.Toplevel()
    topLevel.protocol( 'WM_DELETE_WINDOW' , topLevel.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = topLevel
    _w1 = HtmlWindow(_top1)
    _w1.Custom1.set_html(html)
    global title
    _w1.top.title = title
    topLevel.mainloop()

Custom = tkhtmlview.HTMLScrolledText

def displayReport(htmlContents, windowTitle):
    global html
    global title
    html = htmlContents
    title = windowTitle
    start()

if __name__ == '__main__':
    generic_report.start_up()




