#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 25, 2022 08:33:03 AM PDT  platform: Windows NT
#    Apr 27, 2022 07:12:55 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

from database.employment import CustomerEmployment, generateRandomEmployment
from ui.AddCustomerEmployerForm import AddCustomerEmployerForm

customer = None

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = AddCustomerEmployerForm.Toplevel1(_top1)
    root.mainloop()

def start(*args):
    '''Main entry point for the application.'''
    global topLevel
    topLevel = tk.Toplevel()
    topLevel.protocol('WM_DELETE_WINDOW', topLevel.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = topLevel
    _w1 = AddCustomerEmployerForm.Toplevel1(_top1)
    topLevel.mainloop()

callback = None

def Submit(*args):
    print('AddCustomerEmployerForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

    employment = CustomerEmployment(0, 0, _w1.employerValue.get(),
                                    _w1.titleValue.get(),
                                    _w1.supervisorValue.get(),
                                    _w1.phoneValue.get(),
                                    _w1.addressValue.get(),
                                    _w1.startDateValue.get(),
                                    _w1.endDateValue.get())
    global callback
    if callback is not None:
        callback(employment)

def addEmployer(newCustomer, addEmployerCallback):
    global callback
    global employment
    global customer
    customer = newCustomer
    callback = addEmployerCallback
    employment = None
    start()

def randomData(*args):
    print('AddCustomerEmployerForm_support.randomData')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()
    employment = generateRandomEmployment(customer)
    _w1.employerValue.set(employment.employer)
    _w1.titleValue.set(employment.title)
    _w1.supervisorValue.set(employment.supervisor)
    _w1.phoneValue.set(employment.supervisor_phone)
    _w1.addressValue.set(employment.employer_address)
    _w1.startDateValue.set(employment.start_date)
    _w1.endDateValue.set(employment.end_date)

if __name__ == '__main__':
    AddCustomerEmployerForm.start_up()





