#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Apr 25, 2022 08:33:03 AM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

from database.employment import CustomerEmployment
from ui.AddCustomerEmployerForm import AddCustomerEmployerForm

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = AddCustomerEmployerForm.Toplevel1(_top1)
    root.mainloop()

callback = None

def Submit(*args):
    print('AddCustomerEmployerForm_support.Submit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

    employment = CustomerEmployment(0, 0, _w1.employerValue.get(),
                                    _w1.titleValue.get(),
                                    _w1.supervisorValue.get(),
                                    _w1.phoneValue.get(),
                                    _w1.addressValue.get(),
                                    _w1.startDateValue.get(),
                                    _w1.endDateValue.get())
    global callback
    if callback is not None:
        callback(employment)


def addEmployer(addEmployerCallback):
    global callback
    global employment
    callback = addEmployerCallback
    employment = None
    AddCustomerEmployerForm.start_up()

if __name__ == '__main__':
    AddCustomerEmployerForm.start_up()




